language: python

matrix:
  include:
    - os: linux
      python: 3.4
    #- os: osx
    #  language: generic
  #allow_failures:
  #  - os: osx

install:
  - if [ "$TRAVIS_OS_NAME" == "osx"   ] ; then   mac-build/install.sh ; fi
    pip install pyside
    pip install markdown
    pip install py-gfm
  
  
