language: python

matrix:
  include:
    - os: linux
      python: 3.4
    #- os: osx
    #  language: generic
  #allow_failures:
  #  - os: osx

install:
  - if [ "$TRAVIS_OS_NAME" == "osx"   ] ; then   mac-build/install.sh ; fi
  #- "pip install pyside"
  - sudo apt-get install libqt4-dev
  - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;
  # Travis CI servers use virtualenvs, so we need to finish the install by the following
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
  - "pip install pyinstaller"
  - "pip install toml"
  - "pip install pyYaml"
  - "pip install qdarkstyle"
  - "pip install six"
  - "pip install markdown"
  - "pip install py-gfm"
  - "pip install docutils"
  - "pip install typing"
  
script:
    - "python deploy.py"
