environment:
  matrix:
    - PYTHON: "C:\\Python33"
      MINICONDA_VERSION: "3.3"
      MINICONDA_ARCH: "32"
      
    - PYTHON: "C:\\Python33-x64"
      MINICONDA_VERSION: "3.3"
      MINICONDA_ARCH: "64"
      
    
install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Lib\\site-packages;%PATH%
  - "pip install pyside"
  - "pip install pyinstaller"
  - "pip install toml"
  - "pip install pyYaml"
  - "pip install qdarkstyle"
  - "pip install six"
  - "pip install markdown"
  - "pip install py-gfm"
  - "pip install docutils"
  - "pip install typing"
    
build: off

after_test:
    - "%PYTHON%\\python deploy.py"
    
artifacts:
  - path: sphinx-explorer_*.zip

