environment:
  matrix:
    - MINICONDA: "C:\\Miniconda3"
      MINICONDA_VERSION: "3.4"
      MINICONDA_ARCH: "32"
      
    - MINICONDA: "C:\\Miniconda3-x64"
      MINICONDA_VERSION: "3.4"
      MINICONDA_ARCH: "64"
      
    
install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - "pip install wheel"
  - "pip install setuptools"
  - "pip install pyinstaller"
  - "pip install toml"
  - "pip install pyYaml"
  - "conda install pySide"
  - "pip install qdarkstyle"
  - "pip install six"
  - "pip install markdown"
  - "pip install py-gfm"
  - "pip install docutils"
  - "pip install typing"
    
build: off

after_test:
    - "python deploy.py"
    
artifacts:
  - path: sphinx-explorer_*.zip
