[sourcedir]
name = "Source directory"
value_type = "TypeDirPath"
required = true

[outputdir]
name = "Output directory"
value_type = "TypeDirPath"
required = true

[project]
name = "Project name"
description = """
The project name will occur in several places in the built documentation.
"""
required = true

[author]
name = "Author name"
description = """
Author name
"""
required = true

[separate]
name = "Separate files"
value_type = "TypeBool"
default = false

[private]
name = "Include private module"
value_type = "TypeBool"
default = false


