[params]
[params.outputdir]
label = "Output directory"
value_type = "TypeDirPath"
required = true

[params.project]
label = "Project name"
description = """
The project name will occur in several places in the built documentation.
"""
required = true


[params.author]
label = "Author name"
description = """
Author name
"""
required = true


[params.apidoc-separate]
label = "Separate files"
value_type = "TypeBool"
default = false


[params.apidoc-private]
label = "Include private module"
value_type = "TypeBool"
default = false


[wizard]
_order = [
    "Api document settings",
    "Settings",
]

[wizard."Api document settings"]
params = [
    "outputdir",
    "sourcedir",
]

[wizard."Settings"]
params = [
    "project",
    "author",
    "apidoc-separate",
    "apidoc-private",
]

