[project]
label = "Project name"
description = """
The project name will occur in several places in the built documentation.
"""
required = true

[path]
label = "Root path"
value_type = "TypeDirPath"
link="project"
link_format = "{_default}{_path_sep}{}"

description = """
Root path for documentation.
"""

[author]
label = "Author name"
description = """
Author name
"""

[version]
label = "Version"
description = '''
Sphinx has the notion of a "version" and a "release" for the
software. Each version can have multiple releases. For example, for
Python the version is something like 2.5 or 3.0, while the release is
something like 2.5.1 or 3.0a1.  If you don't need this dual structure,
just set both to the same value.
'''

[release]
label = "Release"
description = '''
Sphinx has the notion of a "version" and a "release" for the
software. Each version can have multiple releases. For example, for
Python the version is something like 2.5 or 3.0, while the release is
something like 2.5.1 or 3.0a1.  If you don't need this dual structure,
just set both to the same value.
'''
link = "version"

[language]
label = "Language"
value_type = "TypeLanguage"
description = '''
For a list of supported codes, see

http://sphinx-doc.org/config.html#confval-language.
'''

[html_theme]
label = "HTML theme"
value_type = "TypeHtmlTheme"
default = "default"
description = """
HTML Theme.
"""

[epub]
label = "Use EPUB"
value_type = "TypeBool"
default = false
description = """
Sphinx can also add configuration for epub output.
"""

[sep]
label = "Separate directories"
value_type = "TypeBool"
default = true
description = '''
You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
'''

[prefix]
label = "Prefix of static directories"
default = "_"
description = '''
Inside the root directory, two more directories will be created; "_templates"
for custom HTML templates and "_static" for custom stylesheets and other static
files. You can enter another prefix (such as ".") to replace the underscore.
'''

[suffix]
label = "Suffix of files"
default = ".rst"
description = '''
The file name suffix for source files. Commonly, this is either ".txt"
or ".rst".  Only files with this suffix are considered documents.
'''

[master]
label = "Master document name"
default = "index"
description = '''
One document is special in that it is considered the top node of the
"contents tree", that is, it is the root of the hierarchical structure
of the documents. Normally, this is "index", but if your "index"
document is a custom template, you can also set this to another filename.
'''

[makefile]
label = "Make Makefile"
value_type = "TypeBool"
default = true
description = '''
A Makefile and a Windows command file can be generated for you so that you
only have to run e.g. `make html' instead of invoking sphinx-build directly.
'''

[batchfile]
label = "Make command file"
value_type = "TypeBool"
default = true
description = '''
A Makefile and a Windows command file can be generated for you so that you
only have to run e.g. `make html' instead of invoking sphinx-build directly.
'''


[apidoc-sourcedir]
label = "Module directory"
value_type = "TypeDirPath"
required = true

[apidoc-separate]
label = "Separate files"
value_type = "TypeBool"
default = false


[apidoc-private]
label = "Include private module"
value_type = "TypeBool"
default = false


["Extensions"]
extensions = [
    "ext-autodoc",
    "ext-doctest",
    "ext-intersphinx",
    "ext-todo",
    "ext-coverage",
    "ext-imgmath",
    "ext-mathjax",
    "ext-ifconfig",
    "ext-viewcode",
    "ext-githubpage",
]

["More Extensions"]
extensions = [
    "ext-commonmark",
    "ext-nbsphinx",
    "ext-fontawesome",
    "ext-blockdiag",
    "ext-autosummary",
]

