["Required params"]
    ["Required params".path]
    name = "Root path"
    value_type = "TypeDirPath"
    default = "."
    description = """
Root path for documentation.
    """

    ["Required params".project]
    name = "Project name"
    description = """
The project name will occur in several places in the built documentation.
    """

    ["Required params".author]
    name = "Author name"
    description = """
Author name
    """

    ["Required params".version]
    name = "Version"
    description = '''
Sphinx has the notion of a "version" and a "release" for the
software. Each version can have multiple releases. For example, for
Python the version is something like 2.5 or 3.0, while the release is
something like 2.5.1 or 3.0a1.  If you don't need this dual structure,
just set both to the same value.
    '''

    ["Required params".release]
    name = "Release"
    description = '''
Sphinx has the notion of a "version" and a "release" for the
software. Each version can have multiple releases. For example, for
Python the version is something like 2.5 or 3.0, while the release is
something like 2.5.1 or 3.0a1.  If you don't need this dual structure,
just set both to the same value.
    '''
    link = "version"


["Document params"]
    ["Document params".language]
    name = "Language"
    value_type = "TypeLanguage"
    description = '''
For a list of supported codes, see

http://sphinx-doc.org/config.html#confval-language.
    '''

    ["Document params".epub]
    name = "Use EPUB"
    value_type = "TypeBool"
    default = false
    description = """
Sphinx can also add configuration for epub output.
    """

    ["Document params".html_theme]
    name = "HTML theme"
    value_type = "TypeHtmlTheme"
    default = "default"
    description = """
HTML Theme.
    """

["Constitution params"]
    ["Constitution params".sep]
    name = "Separate directories"
    value_type = "TypeBool"
    default = false
    description = '''
You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
    '''

    ["Constitution params".prefix]
    name = "Prefix of static directories"
    default = "_"
    description = '''
Inside the root directory, two more directories will be created; "_templates"
for custom HTML templates and "_static" for custom stylesheets and other static
files. You can enter another prefix (such as ".") to replace the underscore.
    '''

    ["Constitution params".suffix]
    name = "Suffix of files"
    default = ".rst"
    description = '''
The file name suffix for source files. Commonly, this is either ".txt"
or ".rst".  Only files with this suffix are considered documents.
    '''

    ["Constitution params".master]
    name = "Master document name"
    default = "index"
    description = '''
One document is special in that it is considered the top node of the
"contents tree", that is, it is the root of the hierarchical structure
of the documents. Normally, this is "index", but if your "index"
document is a custom template, you can also set this to another filename.
    '''

["Build params"]
    ["Build params".makefile]
    name = "Make Makefile"
    value_type = "TypeBool"
    default = true
    description = '''
A Makefile and a Windows command file can be generated for you so that you
only have to run e.g. `make html' instead of invoking sphinx-build directly.
    '''

    ["Build params".batchfile]
    name = "Make command file"
    value_type = "TypeBool"
    default = true
    description = '''
A Makefile and a Windows command file can be generated for you so that you
only have to run e.g. `make html' instead of invoking sphinx-build directly.
    '''

["Extensions"]
["Extensions".autodoc]
name = "autodoc"
value_type = "TypeBool"

["Extensions".doctest]
name = "doctest"
value_type = "TypeBool"

["Extensions".intersphinx]
name = "intersphinx"
value_type = "TypeBool"

["Extensions".todo]
name = "todo"
value_type = "TypeBool"

["Extensions".coverage]
name = "coverage"
value_type = "TypeBool"

["Extensions".imgmath]
name = "imgmath"
value_type = "TypeBool"


["Extensions".mathjax]
name = "mathjax"
value_type = "TypeBool"


["Extensions".ifconfig]
name = "ifconfig"
value_type = "TypeBool"

["Extensions".viewcode]
name = "viewcode"
value_type = "TypeBool"

["Extensions".githubpage]
name = "githubpage"
value_type = "TypeBool"

["More Extensions"]
["More Extensions".commonmark]
name = "commonmark"
value_type = "TypeBool"
package=["CommonMark", "recommonmark"]
conf_py='''
# ----- CommonMark
source_suffix = [source_suffix, '.md']
from recommonmark.parser import CommonMarkParser
source_parsers = {
    '.md': CommonMarkParser,
}
from recommonmark.transform import AutoStructify
github_doc_root = 'https://github.com/rtfd/recommonmark/tree/master/doc/'
def setup(app):
    app.add_config_value('recommonmark_config', {
            'url_resolver': lambda url: github_doc_root + url,
            'auto_toc_tree_section': 'Contents',
            }, True)
    app.add_transform(AutoStructify)
'''

["More Extensions".nbsphinx]
name = "nbsphinx"
value_type = "TypeBool"
conf_py="""
# ----- Jupyter Notebook nbsphinx
extensions.append('nbsphinx')
exclude_patterns.append('**.ipynb_checkpoints')
"""
package=["nbsphinx"]


["More Extensions".fontawesome]
name = "fontawesome"
value_type = "TypeBool"
package=["sphinx-fontawesome"]

