[sphinx_rtd_theme]
packages = ["sphinx_rtd_theme"]
append_conf_py = """
import sphinx_rtd_theme

html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
"""

description = '''
Read The Docs Theme.

```
import sphinx_rtd_theme

html_theme = "sphinx_rtd_theme"

html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
```
'''

[default]
description = """
This is Default Theme.
"""

[basic]

[sphinxdoc]

[agogo]

[nature]

[pyramid]

[haiku]

[epub]

[bizstyle]

