# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tree_view_projects = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_view_projects.sizePolicy().hasHeightForWidth())
        self.tree_view_projects.setSizePolicy(sizePolicy)
        self.tree_view_projects.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tree_view_projects.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tree_view_projects.setRootIsDecorated(False)
        self.tree_view_projects.setObjectName("tree_view_projects")
        self.tree_view_projects.header().setVisible(True)
        self.horizontalLayout_2.addWidget(self.tree_view_projects)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_add = QtWidgets.QToolButton(self.centralwidget)
        self.button_add.setAutoRaise(True)
        self.button_add.setObjectName("button_add")
        self.verticalLayout_3.addWidget(self.button_add)
        self.button_up = QtWidgets.QToolButton(self.centralwidget)
        self.button_up.setAutoRaise(True)
        self.button_up.setObjectName("button_up")
        self.verticalLayout_3.addWidget(self.button_up)
        self.button_down = QtWidgets.QToolButton(self.centralwidget)
        self.button_down.setAutoRaise(True)
        self.button_down.setObjectName("button_down")
        self.verticalLayout_3.addWidget(self.button_down)
        self.button_del = QtWidgets.QToolButton(self.centralwidget)
        self.button_del.setAutoRaise(True)
        self.button_del.setObjectName("button_del")
        self.verticalLayout_3.addWidget(self.button_del)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile_F = QtWidgets.QMenu(self.menubar)
        self.menuFile_F.setObjectName("menuFile_F")
        self.menuCreate_C = QtWidgets.QMenu(self.menubar)
        self.menuCreate_C.setObjectName("menuCreate_C")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dock_outputs = QtWidgets.QDockWidget(MainWindow)
        self.dock_outputs.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dock_outputs.setObjectName("dock_outputs")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plain_output = QConsoleWidget(self.dockWidgetContents)
        self.plain_output.setObjectName("plain_output")
        self.verticalLayout_2.addWidget(self.plain_output)
        self.dock_outputs.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock_outputs)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_add_document = QtWidgets.QAction(MainWindow)
        self.action_add_document.setObjectName("action_add_document")
        self.action_settings = QtWidgets.QAction(MainWindow)
        self.action_settings.setObjectName("action_settings")
        self.action_wizard = QtWidgets.QAction(MainWindow)
        self.action_wizard.setObjectName("action_wizard")
        self.action_apidoc = QtWidgets.QAction(MainWindow)
        self.action_apidoc.setObjectName("action_apidoc")
        self.action_reload = QtWidgets.QAction(MainWindow)
        self.action_reload.setObjectName("action_reload")
        self.action_move_up = QtWidgets.QAction(MainWindow)
        self.action_move_up.setObjectName("action_move_up")
        self.action_move_down = QtWidgets.QAction(MainWindow)
        self.action_move_down.setObjectName("action_move_down")
        self.action_delete_document = QtWidgets.QAction(MainWindow)
        self.action_delete_document.setObjectName("action_delete_document")
        self.menuFile_F.addAction(self.action_settings)
        self.menuCreate_C.addAction(self.action_wizard)
        self.menuCreate_C.addAction(self.action_apidoc)
        self.menubar.addAction(self.menuFile_F.menuAction())
        self.menubar.addAction(self.menuCreate_C.menuAction())
        self.toolBar.addAction(self.action_wizard)
        self.toolBar.addAction(self.action_apidoc)
        self.toolBar.addAction(self.action_settings)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sphinx Explorer"))
        self.button_add.setText(_translate("MainWindow", "..."))
        self.button_up.setText(_translate("MainWindow", "..."))
        self.button_down.setText(_translate("MainWindow", "..."))
        self.button_del.setText(_translate("MainWindow", "..."))
        self.menuFile_F.setTitle(_translate("MainWindow", "File(&F)"))
        self.menuCreate_C.setTitle(_translate("MainWindow", "Create(&C)"))
        self.dock_outputs.setWindowTitle(_translate("MainWindow", "Outputs"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_add_document.setText(_translate("MainWindow", "Add Document"))
        self.action_add_document.setToolTip(_translate("MainWindow", "Add Document"))
        self.action_settings.setText(_translate("MainWindow", "Settings..."))
        self.action_settings.setToolTip(_translate("MainWindow", "Settings"))
        self.action_settings.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_wizard.setText(_translate("MainWindow", "wizard mode"))
        self.action_wizard.setToolTip(_translate("MainWindow", "wizard mode"))
        self.action_apidoc.setText(_translate("MainWindow", "apidoc"))
        self.action_apidoc.setToolTip(_translate("MainWindow", "apidoc"))
        self.action_reload.setText(_translate("MainWindow", "リロード"))
        self.action_reload.setToolTip(_translate("MainWindow", "リロード"))
        self.action_reload.setShortcut(_translate("MainWindow", "F5"))
        self.action_move_up.setText(_translate("MainWindow", "Move up"))
        self.action_move_up.setToolTip(_translate("MainWindow", "Move up"))
        self.action_move_up.setShortcut(_translate("MainWindow", "Ctrl+Up"))
        self.action_move_down.setText(_translate("MainWindow", "Move down"))
        self.action_move_down.setToolTip(_translate("MainWindow", "Move down"))
        self.action_move_down.setShortcut(_translate("MainWindow", "Ctrl+Down"))
        self.action_delete_document.setText(_translate("MainWindow", "Delete document"))
        self.action_delete_document.setToolTip(_translate("MainWindow", "Delete document"))
        self.action_delete_document.setShortcut(_translate("MainWindow", "Del"))

from ..util.QConsoleWidget import QConsoleWidget
