# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/toshiyuki/sphinx-explorer/sphinx_explorer/main_window.ui'
#
# Created: Sun Apr  9 00:27:58 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tool_button_quick_start = QtGui.QToolButton(self.centralwidget)
        self.tool_button_quick_start.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tool_button_quick_start.setObjectName("tool_button_quick_start")
        self.horizontalLayout.addWidget(self.tool_button_quick_start)
        self.tool_add_document = QtGui.QToolButton(self.centralwidget)
        self.tool_add_document.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tool_add_document.setObjectName("tool_add_document")
        self.horizontalLayout.addWidget(self.tool_add_document)
        self.tool_setting = QtGui.QToolButton(self.centralwidget)
        self.tool_setting.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tool_setting.setObjectName("tool_setting")
        self.horizontalLayout.addWidget(self.tool_setting)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tree_view_projects = QtGui.QTreeView(self.splitter)
        self.tree_view_projects.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tree_view_projects.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tree_view_projects.setObjectName("tree_view_projects")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile_F = QtGui.QMenu(self.menubar)
        self.menuFile_F.setObjectName("menuFile_F")
        self.menuCreate_C = QtGui.QMenu(self.menubar)
        self.menuCreate_C.setObjectName("menuCreate_C")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dock_outputs = QtGui.QDockWidget(MainWindow)
        self.dock_outputs.setObjectName("dock_outputs")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plain_output = QConsoleWidget(self.dockWidgetContents)
        self.plain_output.setObjectName("plain_output")
        self.verticalLayout_2.addWidget(self.plain_output)
        self.dock_outputs.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock_outputs)
        self.action_add_document = QtGui.QAction(MainWindow)
        self.action_add_document.setObjectName("action_add_document")
        self.action_settings = QtGui.QAction(MainWindow)
        self.action_settings.setObjectName("action_settings")
        self.action_wizard = QtGui.QAction(MainWindow)
        self.action_wizard.setObjectName("action_wizard")
        self.action_apidoc = QtGui.QAction(MainWindow)
        self.action_apidoc.setObjectName("action_apidoc")
        self.menuFile_F.addAction(self.action_settings)
        self.menuCreate_C.addAction(self.action_apidoc)
        self.menubar.addAction(self.menuFile_F.menuAction())
        self.menubar.addAction(self.menuCreate_C.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Sphinx Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.tool_button_quick_start.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.tool_add_document.setText(QtGui.QApplication.translate("MainWindow", "add document", None, QtGui.QApplication.UnicodeUTF8))
        self.tool_setting.setText(QtGui.QApplication.translate("MainWindow", "Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile_F.setTitle(QtGui.QApplication.translate("MainWindow", "File(&F)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreate_C.setTitle(QtGui.QApplication.translate("MainWindow", "Create(&C)", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_outputs.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_document.setText(QtGui.QApplication.translate("MainWindow", "Add Document", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_document.setToolTip(QtGui.QApplication.translate("MainWindow", "Add Document", None, QtGui.QApplication.UnicodeUTF8))
        self.action_settings.setText(QtGui.QApplication.translate("MainWindow", "Settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_settings.setToolTip(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.action_settings.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_wizard.setText(QtGui.QApplication.translate("MainWindow", "wizard mode", None, QtGui.QApplication.UnicodeUTF8))
        self.action_wizard.setToolTip(QtGui.QApplication.translate("MainWindow", "wizard mode", None, QtGui.QApplication.UnicodeUTF8))
        self.action_apidoc.setText(QtGui.QApplication.translate("MainWindow", "apidoc", None, QtGui.QApplication.UnicodeUTF8))
        self.action_apidoc.setToolTip(QtGui.QApplication.translate("MainWindow", "apidoc", None, QtGui.QApplication.UnicodeUTF8))

from .util.QConsoleWidget import QConsoleWidget
